### PR TITLE
Fix GPG key for packages

### LINKED ISSUE #10: Duo GPG key is no longer available on pgp.mit.edu
The key is no longer able to be pulled from pgp.mit.edu resulting in a failure when trying to install from package. The key is available at https://duo.com/APT-GPG-KEY-DUO. I'll have a pull together shortly to correct this.

### PR DESCRIPTION
**Pull request by mattlqx**
Fixes #10 

Changes to fetch key from Duo.com and bumps package version to latest.

### CODE REVIEW

**Comment by fromonesrc** [comment]
:thumbsup: thanks

**Comment by jacknagz** [comment]
hey @mattlqx can you tag a release and upload to supermarket?

**Comment by mattlqx** [comment]
Ah, I'm not a collaborator for the Supermarket project. @fromonesrc will have to handle that.

**Comment by fromonesrc** [comment]
@mattlqx would you be interested in taking ownership of this cookbook?

**Comment by mattlqx** [comment]
Sure, why not. :)

**Comment by fromonesrc** [comment]
What's your chef supermarket username?

**Comment by mattlqx** [comment]
mkulka, thanks!

**Comment by fromonesrc** [comment]
Transfer of github and supermarket repos initiated. Thanks @mattlqx!

**Comment by mattlqx** [comment]
Great, I'll get Supermarket updated after everything settles. Thanks for creating the cookbook! It's important to my environments so I should be able to maintain it for a good while.

**Pull request merged**
